# Generated by Django 3.1.2 on 2021-01-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0006_auto_20210121_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='event date')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
    ]
