# Generated by Django 3.1.2 on 2020-12-06 14:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ba33dc65-a0f7-412f-995f-86c7db2d841a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('deadline', models.DateField(verbose_name='date to end')),
                ('body', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/<function dir_name at 0x7f68cf377790>')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c82db4a2-4a95-4aec-8ddc-a070ef10a849'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('message', models.TextField(blank=True, max_length=4000, null=True)),
                ('feedback', models.TextField(blank=True, max_length=4000, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='done_tasks/<property object at 0x7f68ccbbedb0>')),
                ('status', models.SmallIntegerField(choices=[(1, 'Not done'), (2, 'Done'), (3, 'To edit')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_done', to='subjects.task')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='subjects.Teacher'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b127578a-0262-47a7-a35b-06e701c47115'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=4000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/<property object at 0x7f68ccbbe040>')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='PostInSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.task')),
            ],
        ),
        migrations.CreateModel(
            name='CommentInSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subjects.postinsubject')),
            ],
        ),
    ]
