# Generated by Django 3.1.2 on 2020-12-06 14:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/<property object at 0x7fd556535310>'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7bc8dba-cb49-4049-a1e8-c1ed06351621'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/to_do/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea3185ac-c5fb-427b-870e-9e5513090b55'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='done_tasks/<property object at 0x7fd556535d60>'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cbe661d7-1884-4e4b-9c40-0d530ca90200'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
