# Generated by Django 3.1.2 on 2020-11-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='done_tasks/<built-in function id>/'),
        ),
    ]
