# Generated by Django 3.1.2 on 2020-12-15 21:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20201206_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.UUID('04d21fb0-5bb2-45cd-9ed1-3075c645b067'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27a9fa15-2a44-467d-9f8d-d5cb865baa76'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='done_tasks/<property object at 0x7f9b44134e50>'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3ddc11cf-7b2a-4b5e-9573-9cceb67cf57e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
