# Generated by Django 3.1.2 on 2020-12-19 21:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20201215_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ba494fd-3bb7-41ef-b91f-10f7fe5b0fc9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('31595902-d4f9-49ad-9fdf-15bf8fd7646a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='done_tasks/'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ce3efbe-2131-4990-81b2-b04a9d894c1e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
