# Generated by Django 3.1.2 on 2020-11-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_taskdone_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=4000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/<built-in function id>/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subjects.subject')),
            ],
        ),
    ]
