# Generated by Django 3.1.2 on 2020-12-26 14:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20201219_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9949e73-4a6a-4756-9e4b-5b391b2a547e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2661ffe-9f99-4604-8d3b-2c04daa1d98e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44aaa813-63a5-4dd4-8479-8e93ecccac20'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='TeacherToSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='subjects.teacher')),
            ],
        ),
    ]
