# Generated by Django 3.1.2 on 2021-01-21 18:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20201226_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4b13acb-4954-44a7-b5f2-ab1815117c88'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a10c37ef-4fb3-4334-aff4-5e9728c7684f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9b285561-d023-41ae-9955-054d0eb8c770'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
