# Generated by Django 3.1.2 on 2020-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20201127_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/<property object at 0x7f3b00614450>'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/<property object at 0x7f3b00614090>'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='done_tasks/<property object at 0x7f3b00614d60>'),
        ),
    ]
