# Generated by Django 3.1.2 on 2020-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20201127_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/<property object at 0x7f0b12aa0310>'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks\\<property object at 0x7f0b12d47680>'),
        ),
        migrations.AlterField(
            model_name='taskdone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='done_tasks/<property object at 0x7f0b10112d10>'),
        ),
    ]
